import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import { getTenantSettings } from '@/lib/api';
import { CartProvider } from '@/context/CartContext';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const settings = await getTenantSettings();

  const cssVars = settings
    ? `
    :root {
      --color-primary: ${settings.colorPrimary ?? '#8B6914'};
      --color-secondary: ${settings.colorSecondary ?? '#F5EFE6'};
      --color-accent: ${settings.colorAccent ?? '#C4956A'};
      --color-text: ${settings.colorText ?? '#2C2C2C'};
      --color-background: ${settings.colorBackground ?? '#FAFAF8'};
      --font-family: ${settings.fontFamily ?? 'Inter'};
      --border-radius: ${settings.borderRadius ?? '8px'};
    }
  `
    : '';

  return (
    <html
      lang="tr"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        {cssVars && <style dangerouslySetInnerHTML={{ __html: cssVars }} />}
        <title></title>
      </head>
      <body
        className="min-h-full flex flex-col"
        style={{ backgroundColor: settings?.colorBackground ?? '#FAFAF8' }}
      >
        <CartProvider>
          <Header />
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
